services:
  node:
    build: .
    # networks:
    #   - rest-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    restart: always

  database:
    build: ./database
    # networks:
    #   - rest-network
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/logs:/var/lib/postgresql/data/log
    # volumes:
    #   - ./database/data:/var/lib/postgresql/data
    restart: always
networks:
  rest-network:
    driver: bridge
volumes:
  pgdata:
