services:
  node:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    depends_on:
      - database

  database:
    build: ./database
    ports:
      - '$POSTGRES_PORT:$POSTGRES_PORT'
    restart: on-failure
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
